services:
  pysindy:
    build:
      context: .
      dockerfile: pysindy/Dockerfile
    volumes:
      - ./data:/app/data:ro
      - ./results:/app/results

  epde:
    build:
      context: .
      dockerfile: epde/Dockerfile
    deploy:  # ‚Üê Docker Desktop requires this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./data:/app/data:ro
      - ./results:/app/results

  # discover:
  #   build:
  #     context: .
  #     dockerfile: discover/Dockerfile
  #   volumes:
  #     - ./data:/app/data:ro
  #     - ./results:/app/results
  