services:
  pysindy:
    build:
      context: .
      dockerfile: pysindy/Dockerfile
    volumes:
      - ./data:/app/data:ro
      - ./results:/app/results

  epde:
    build:
      context: .
      dockerfile: epde/Dockerfile
    volumes:
      - ./data:/app/data:ro
      - ./results:/app/results
  