services:
  pysindy:
    build:
      context: .
      dockerfile: pysindy/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./data:/app/data:ro
      - ./results:/app/results

  epde:
    build:
      context: .
      dockerfile: epde/Dockerfile
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./data:/app/data:ro
      - ./results:/app/results

  discover:
    build:
      context: .
      dockerfile: discover/Dockerfile
    deploy:  
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./data:/app/data:ro
      - ./results:/app/results
  
  # sga-pde:
  #   build:
  #     context: .
  #     dockerfile: sga-pde/Dockerfile
  #   deploy:  
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #   volumes:
  #     - ./data:/app/data:ro
  #     - ./results:/app/results
  
  deepmod:
    build:
      context: .
      dockerfile: deepmod/Dockerfile
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./data:/app/data:ro
      - ./results:/app/results
  